stages:
  prediction-plots:
    cmd: output/glad-shape-197/trained_model.pth -d solar_dataset.json -d stats.pkl
      -o pred-output/ python -m vit.scripts.predictions_analyze
    deps:
    - vit/scripts/predictions_analyze.py
