stages:
  prediction-plots:
    cmd: python -m vit.scripts.predictions_analyze
    deps:
    - output/glad-shape-197/trained_model.pth
    - solar_dataset.json
    - stats.pkl
    outs:
    - pred-output/
