channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - sunpy
  - sunkit-instruments
  - xarray
  - aiapy
  - nc-time-axis
  - beautifulsoup4
  - seaborn
  - scikit-image
  - pip
  - wandb=0.15
  - conda-forge::tensorflow
  - pip:
    - git+https://github.com/linnabraham/astro-utils.git
    - git+https://github.com/linnabraham/ml-scripts.git
