channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sunpy
  - sunkit-instruments
  - xarray
  - aiapy
  - nc-time-axis
  - beautifulsoup4
  - pip
  - pip:
    - git+https://github.com/linnabraham/astro-utils.git
    - git+https://github.com/linnabraham/ml-scripts.git
