#!/usr/bin/env python
"""
generate_pipeline_docs.py

Reads dvc.yaml and writes docs/pipeline.md automatically.
Run this whenever dvc.yaml changes:

    python generate_pipeline_docs.py

Or hook it into mkdocs by adding to mkdocs.yml hooks (see bottom of file).
"""

import yaml
from pathlib import Path

DVC_YAML  = Path("dvc.yaml")
OUTPUT_MD = Path("docs/pipeline.md")
DETAILED_MD = Path("docs/pipeline_details.md")


def load_dvc(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def format_list(items: list[str]) -> str:
    """Format a list of paths as inline code, comma separated."""
    return ", ".join(f"`{i}`" for i in items) if items else "—"

def generate_detailed_stages_md(stages: dict) -> str:
    lines = []
    lines.append("# Detailed Pipeline Stages\n")
    lines.append(
        "_Auto-generated from `dvc.yaml`. "
        "Do not edit this file manually — run `generate_pipeline_docs.py` instead._\n"
    )
    # ── Summary table ────────────────────────────────────────
    lines.append("## Stages\n")
    lines.append("| Stage | Command | Outputs |")
    lines.append("|---|---|---|")

    for name, info in stages.items():
        cmd  = f"`{info.get('cmd', '—')}`"
        outs = info.get("outs", [])
        # outs can be list of str or list of dict (when cache: false)
        out_names = []
        for o in outs:
            if isinstance(o, str):
                out_names.append(o)
            elif isinstance(o, dict):
                out_names.extend(o.keys())
        outs_str = format_list(out_names) if out_names else "—"
        lines.append(f"| `{name}` | {cmd} | {outs_str} |")

    lines.append("")

    # ── Per-stage detail ─────────────────────────────────────
    lines.append("## Stage Details\n")

    for name, info in stages.items():
        lines.append(f"### `{name}`\n")
        lines.append(f"**Command**\n```bash\n{info.get('cmd', '')}\n```\n")

        deps = info.get("deps", [])
        if deps:
            lines.append("**Dependencies**\n")
            for d in deps:
                lines.append(f"- `{d}`")
            lines.append("")

        outs = info.get("outs", [])
        if outs:
            lines.append("**Outputs**\n")
            for o in outs:
                if isinstance(o, str):
                    lines.append(f"- `{o}`")
                elif isinstance(o, dict):
                    for path, meta in o.items():
                        cached = meta.get("cache", True) if meta else True
                        note   = "" if cached else " _(not cached)_"
                        lines.append(f"- `{path}`{note}")
            lines.append("")

        lines.append("---\n")
    return "\n".join(lines)

def generate_markdown(stages: dict) -> str:
    lines = []

    lines.append("# Pipeline\n")
    lines.append(
        "_Auto-generated from `dvc.yaml`. "
        "Do not edit this file manually — run `generate_pipeline_docs.py` instead._\n"
    )
    lines.append("Run the full pipeline with:\n")
    lines.append("```bash\ndvc repro\n```\n")

    # My section
    lines.append("## Stages\n")
    for name, info in stages.items():
        lines.append(f"- [{name}](stages/{name}.md)\n")
    return "\n".join(lines)

def generate_stage_page(name: str, info: dict) -> str:
    lines = []
    lines.append(f"# `{name}`\n")
    lines.append("**Command**")
    lines.append(f"```bash\n{info.get('cmd', '')}\n```\n")
    
    # auto-filled from dvc.yaml
    deps = info.get("deps", [])
    if deps:
        lines.append("**Dependencies**")
        for d in deps:
            lines.append(f"- `{d}`")
        lines.append("")

    outs = info.get("outs", [])
    if outs:
        lines.append("**Outputs**")
        for o in outs:
            if isinstance(o, str):
                lines.append(f"- `{o}`")
            elif isinstance(o, dict):
                for path, meta in o.items():
                    cached = meta.get("cache", True) if meta else True
                    note = "" if cached else " _(not cached)_"
                    lines.append(f"- `{path}`{note}")
        lines.append("")

    # manual section — you fill this in, script never overwrites it
    lines.append("## Notes\n")
    lines.append("_Add your notes about this stage here._\n")

    return "\n".join(lines)

if __name__ == "__main__":
    data   = load_dvc(DVC_YAML)
    stages = data.get("stages", {})
    md     = generate_markdown(stages)

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(md)
    print(f"Written to {OUTPUT_MD}  ({len(stages)} stages)")

    # write summary of stages
    md     = generate_detailed_stages_md(stages)
    DETAILED_MD.parent.mkdir(parents=True, exist_ok=True)
    DETAILED_MD.write_text(md)
    print(f"Written to {DETAILED_MD}  ({len(stages)} stages)")

    # write per-stage pages — but only if they don't exist yet
    stage_dir = Path("docs/stages")
    stage_dir.mkdir(parents=True, exist_ok=True)

    for name, info in stages.items():
        page = stage_dir / f"{name}.md"
        if not page.exists():                   # ← key line
            page.write_text(generate_stage_page(name, info))
            print(f"  Created {page}")
        else:
            print(f"  Skipped {page} (already exists)")
