channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - tensorflow
  - wandb=0.15
  - matplotlib=3.8
  - dvc
  - dvc-gdrive
  - pandas
  - lightning
  - scikit-learn
  - vit-pytorch<=1.10
  - captum
  - sunpy
  - sunkit-instruments
  - xgboost
  - gdown
  - scienceplots
  - seaborn
  - setuptools<=81.0
  - mkdocs-material=9.7
  - mkdocstrings
  - mkdocstrings-python
  - pip
  - pip:
    - git+https://github.com/linnabraham/astro-utils.git
    - git+https://github.com/linnabraham/ml-scripts.git
