channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - pandas
  - wandb
  - lightning
  - scikit-learn
  - vit-pytorch
  - captum
  - sunpy
  - sunkit-instruments
  - xgboost
  - pip
  - pip:
    - git+https://github.com/linnabraham/astro-utils.git
    - git+https://github.com/linnabraham/ml-scripts.git
