import json
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

def load_and_process(json_path):
    with open(json_path, 'r') as f:
        data = json.load(f)

    # Flatten the nested JSON structure for Pandas
    rows = []
    for entry in data:
        row = {
            'round': entry['round'],
            'label': entry['label']
        }
        # Merge the importance dictionary into the row
        row.update(entry['importance'])
        rows.append(row)

    return pd.DataFrame(rows)

def run_statistics(df):
    # Get AIA channel columns (exclude metadata)
    channels = [col for col in df.columns if col.startswith('AIA_')]

    print("\n" + "="*30)
    print("GLOBAL IMPORTANCE STATISTICS")
    print("="*30)

    results = []
    for ch in channels:
        mean_val = df[ch].mean()
        std_dev = df[ch].std()
        stderr = stats.sem(df[ch])

        # One-sample t-test: Is the importance significantly different from 0?
        t_stat, p_val = stats.ttest_1samp(df[ch], 0)

        results.append({
            'Channel': ch,
            'Mean_SHAP': mean_val,
            'Std_Err': stderr,
            'P_Value': p_val,
            'Significant': p_val < 0.05
        })

    stat_df = pd.DataFrame(results).sort_values(by='Mean_SHAP', ascending=False)
    print(stat_df.to_string(index=False))
    return stat_df

def plot_results(df, output_dir):
    channels = [col for col in df.columns if col.startswith('AIA_')]
    df_melted = df.melt(id_vars=['round', 'label'], value_vars=channels, 
                        var_name='Passband', value_name='SHAP_Value')

    plt.figure(figsize=(12, 7))
    sns.set_style("whitegrid")

    # Boxplot shows distribution and medians
    sns.boxplot(data=df_melted, x='Passband', y='SHAP_Value', palette='flare', showfliers=False)

    # Stripplot overlays individual points to see the 50 samples
    sns.stripplot(data=df_melted, x='Passband', y='SHAP_Value', 
                  color='black', alpha=0.3, size=4, jitter=True)

    plt.axhline(0, color='red', linestyle='--', linewidth=1.5)
    plt.title(f'Statistical Significance of Passband Importance (N={len(df)})', fontsize=14)
    plt.ylabel('Mean SHAP Attribution (Importance Score)')
    plt.xlabel('Solar Passband (AIA)')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "significance_plot.png"), dpi=300)
    print(f"\nPlot saved to {output_dir}/significance_plot.png")

if __name__ == "__main__":
    # Path to the JSON generated by the main script
    JSON_FILE = "shap_stats.json"
    OUTPUT_DIR = "plots/kshap/results"

    if os.path.exists(JSON_FILE):
        dataframe = load_and_process(JSON_FILE)
        run_statistics(dataframe)
        if not os.path.exists(OUTPUT_DIR):
            os.makedirs(OUTPUT_DIR, exist_ok=True)
        plot_results(dataframe, OUTPUT_DIR)
    else:
        print(f"Error: {JSON_FILE} not found. Run the attribution script first.")
