channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pandas
  - wandb
  - lightning
  - scikit-learn
  - vit-pytorch
  - captum
  - sunpy
  - pip
  - pip:
    - git+https://github.com/linnabraham/astro-utils.git
    - git+https://github.com/linnabraham/ml-scripts.git
